// Offline German-Polish dictionary (~200 most common words)
const OFFLINE_DICT = {
  // Rodzajniki
  "der": "rodzajnik m.",
  "die": "rodzajnik f./pl.",
  "das": "rodzajnik n.",
  "ein": "jeden/pewien",
  "eine": "jedna/pewna",
  "einen": "jednego/pewnego",
  "einem": "jednemu/pewnemu",
  "einer": "jednej/pewnej",
  "eines": "jednego/pewnego (n.)",

  // Zaimki osobowe
  "ich": "ja",
  "du": "ty",
  "er": "on",
  "sie": "ona/oni/Pan/Pani",
  "es": "ono",
  "wir": "my",
  "ihr": "wy",

  // Zaimki wskazujące i pytajne
  "dieser": "ten",
  "diese": "ta/te",
  "dieses": "to",
  "was": "co",
  "wer": "kto",
  "wo": "gdzie",
  "woher": "skąd",
  "wohin": "dokąd",
  "wann": "kiedy",
  "warum": "dlaczego",
  "wie": "jak",
  "welcher": "który",
  "welche": "która/które",
  "welches": "które (n.)",

  // Spójniki i partykuły
  "und": "i",
  "oder": "lub/albo",
  "aber": "ale",
  "denn": "bo/ponieważ",
  "weil": "ponieważ",
  "wenn": "kiedy/jeśli",
  "dass": "że",
  "als": "kiedy/jako/niż",
  "ob": "czy",
  "also": "więc/zatem",
  "doch": "jednak/przecież",
  "noch": "jeszcze",
  "schon": "już",
  "nur": "tylko",
  "auch": "też/również",
  "nicht": "nie",
  "kein": "żaden",
  "keine": "żadna/żadne",
  "ja": "tak",
  "nein": "nie",
  "vielleicht": "może",
  "denn": "więc/bo",
  "dann": "wtedy/potem",
  "jetzt": "teraz",
  "heute": "dzisiaj",
  "gestern": "wczoraj",
  "morgen": "jutro/rano",
  "immer": "zawsze",
  "nie": "nigdy",
  "oft": "często",
  "manchmal": "czasami",
  "sehr": "bardzo",
  "zu": "za/do",
  "so": "tak/więc",
  "hier": "tutaj",
  "dort": "tam",
  "da": "tam/tu/ponieważ",

  // Przyimki
  "in": "w",
  "an": "przy/na",
  "auf": "na",
  "mit": "z",
  "von": "od/z",
  "aus": "z/ze",
  "nach": "po/do",
  "bei": "przy/u",
  "vor": "przed",
  "hinter": "za/z tyłu",
  "über": "nad/o",
  "unter": "pod",
  "neben": "obok",
  "zwischen": "między",
  "durch": "przez",
  "für": "dla/za",
  "gegen": "przeciw/około",
  "ohne": "bez",
  "um": "około/o",
  "bis": "do/aż",
  "seit": "od (czasu)",
  "während": "podczas",
  "wegen": "z powodu",

  // Podstawowe czasowniki
  "sein": "być",
  "haben": "mieć",
  "werden": "stać się/zostać",
  "können": "móc/umieć",
  "müssen": "musieć",
  "wollen": "chcieć",
  "sollen": "powinien",
  "dürfen": "wolno/móc",
  "mögen": "lubić",
  "möchten": "chciałby",
  "gehen": "iść",
  "kommen": "przychodzić",
  "machen": "robić",
  "sagen": "mówić/powiedzieć",
  "geben": "dawać",
  "nehmen": "brać",
  "sehen": "widzieć",
  "wissen": "wiedzieć",
  "denken": "myśleć",
  "fragen": "pytać",
  "antworten": "odpowiadać",
  "sprechen": "mówić",
  "hören": "słyszeć",
  "lesen": "czytać",
  "schreiben": "pisać",
  "lernen": "uczyć się",
  "arbeiten": "pracować",
  "wohnen": "mieszkać",
  "leben": "żyć",
  "kaufen": "kupować",
  "verkaufen": "sprzedawać",
  "essen": "jeść",
  "trinken": "pić",
  "schlafen": "spać",
  "spielen": "grać/bawić się",
  "laufen": "biec/chodzić",
  "fahren": "jechać",
  "finden": "znajdować",
  "kennen": "znać",
  "zeigen": "pokazywać",
  "verstehen": "rozumieć",
  "helfen": "pomagać",
  "brauchen": "potrzebować",
  "bleiben": "pozostawać",
  "heißen": "nazywać się",
  "öffnen": "otwierać",
  "schließen": "zamykać",
  "beginnen": "zaczynać",
  "enden": "kończyć",
  "stehen": "stać",
  "sitzen": "siedzieć",
  "liegen": "leżeć",
  "bringen": "przynosić",
  "lassen": "zostawić/pozwolić",
  "halten": "trzymać",
  "glauben": "wierzyć/myśleć",
  "versuchen": "próbować",
  "suchen": "szukać",
  "treffen": "spotykać",

  // Liczebniki 1-20
  "null": "zero",
  "eins": "jeden",
  "zwei": "dwa",
  "drei": "trzy",
  "vier": "cztery",
  "fünf": "pięć",
  "sechs": "sześć",
  "sieben": "siedem",
  "acht": "osiem",
  "neun": "dziewięć",
  "zehn": "dziesięć",
  "elf": "jedenaście",
  "zwölf": "dwanaście",
  "dreizehn": "trzynaście",
  "vierzehn": "czternaście",
  "fünfzehn": "piętnaście",
  "sechzehn": "szesnaście",
  "siebzehn": "siedemnaście",
  "achtzehn": "osiemnaście",
  "neunzehn": "dziewiętnaście",
  "zwanzig": "dwadzieścia",
  "dreißig": "trzydzieści",
  "vierzig": "czterdzieści",
  "fünfzig": "pięćdziesiąt",
  "hundert": "sto",
  "tausend": "tysiąc",

  // Dni tygodnia
  "montag": "poniedziałek",
  "dienstag": "wtorek",
  "mittwoch": "środa",
  "donnerstag": "czwartek",
  "freitag": "piątek",
  "samstag": "sobota",
  "sonntag": "niedziela",

  // Miesiące
  "januar": "styczeń",
  "februar": "luty",
  "märz": "marzec",
  "april": "kwiecień",
  "mai": "maj",
  "juni": "czerwiec",
  "juli": "lipiec",
  "august": "sierpień",
  "september": "wrzesień",
  "oktober": "październik",
  "november": "listopad",
  "dezember": "grudzień",

  // Kolory
  "rot": "czerwony",
  "blau": "niebieski",
  "grün": "zielony",
  "gelb": "żółty",
  "weiß": "biały",
  "schwarz": "czarny",
  "grau": "szary",
  "braun": "brązowy",
  "orange": "pomarańczowy",
  "lila": "fioletowy",
  "rosa": "różowy",
  "dunkel": "ciemny",
  "hell": "jasny",

  // Podstawowe rzeczowniki
  "mann": "mężczyzna",
  "frau": "kobieta",
  "kind": "dziecko",
  "mensch": "człowiek",
  "name": "imię/nazwa",
  "haus": "dom",
  "wohnung": "mieszkanie",
  "zimmer": "pokój",
  "tür": "drzwi",
  "fenster": "okno",
  "tisch": "stół",
  "stuhl": "krzesło",
  "bett": "łóżko",
  "stadt": "miasto",
  "land": "kraj/wieś",
  "straße": "ulica",
  "schule": "szkoła",
  "arbeit": "praca",
  "beruf": "zawód",
  "geld": "pieniądze",
  "zeit": "czas",
  "tag": "dzień",
  "nacht": "noc",
  "woche": "tydzień",
  "monat": "miesiąc",
  "jahr": "rok",
  "stunde": "godzina",
  "minute": "minuta",
  "wasser": "woda",
  "essen": "jedzenie",
  "brot": "chleb",
  "buch": "książka",
  "wort": "słowo",
  "satz": "zdanie",
  "sprache": "język",
  "deutsch": "język niemiecki/po niemiecku",
  "freund": "przyjaciel/chłopak",
  "freundin": "przyjaciółka/dziewczyna",
  "familie": "rodzina",
  "mutter": "matka",
  "vater": "ojciec",
  "bruder": "brat",
  "schwester": "siostra",
  "auto": "samochód",
  "zug": "pociąg",
  "bus": "autobus",
  "flugzeug": "samolot",
  "bahnhof": "dworzec",

  // Podstawowe przymiotniki
  "gut": "dobry",
  "schlecht": "zły/niedobry",
  "groß": "duży/wielki",
  "klein": "mały",
  "alt": "stary",
  "neu": "nowy",
  "jung": "młody",
  "schön": "piękny/ładny",
  "hässlich": "brzydki",
  "schnell": "szybki",
  "langsam": "powolny",
  "leicht": "łatwy/lekki",
  "schwer": "trudny/ciężki",
  "billig": "tani",
  "teuer": "drogi",
  "richtig": "prawidłowy/właściwy",
  "falsch": "błędny/fałszywy",
  "gleich": "taki sam/zaraz",
  "anders": "inny",
  "wichtig": "ważny",
  "interessant": "interesujący",
  "langweilig": "nudny",
  "müde": "zmęczony",
  "krank": "chory",
  "gesund": "zdrowy",
  "glücklich": "szczęśliwy",
  "traurig": "smutny",
  "warm": "ciepły",
  "kalt": "zimny",
  "heiß": "gorący",
  "sauber": "czysty",
  "schmutzig": "brudny",
  "voll": "pełny",
  "leer": "pusty",
  "offen": "otwarty",
  "geschlossen": "zamknięty",
  "möglich": "możliwy",
  "unmöglich": "niemożliwy",
};
